// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewStudent struct {
	Name  string `json:"name"`
	Age   int    `json:"age"`
	Email string `json:"email"`
}

type NewTeacher struct {
	Name      string   `json:"name"`
	StudentID []string `json:"student_id"`
}

type Query struct {
}

type Student struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Age   int    `json:"age"`
	Email string `json:"email"`
}

type Teacher struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Students []*Student `json:"students"`
}
